"""add insiders and insider_trades

Revision ID: 2b1e04876168
Revises: f91ac0080dcd
Create Date: 2026-09-20 12:00:32.611718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1e04876168'
down_revision: Union[str, Sequence[str], None] = 'f91ac0080dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insiders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insiders_cik'), 'insiders', ['cik'], unique=True)
    op.create_table('insider_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insider_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('accession_no', sa.String(length=25), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_code', sa.String(length=2), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('shares_owned_after', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('is_director', sa.Boolean(), nullable=False),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.Column('is_ten_percent_owner', sa.Boolean(), nullable=False),
    sa.Column('officer_title', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['insider_id'], ['insiders.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_no', 'insider_id', 'ticker_id', 'transaction_date', 'transaction_code', 'shares', name='uq_insider_trade_natural_key')
    )
    op.create_index(op.f('ix_insider_trades_accession_no'), 'insider_trades', ['accession_no'], unique=False)
    op.create_index(op.f('ix_insider_trades_filed_date'), 'insider_trades', ['filed_date'], unique=False)
    op.create_index(op.f('ix_insider_trades_insider_id'), 'insider_trades', ['insider_id'], unique=False)
    op.create_index(op.f('ix_insider_trades_ticker_id'), 'insider_trades', ['ticker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insider_trades_ticker_id'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_insider_id'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_filed_date'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_accession_no'), table_name='insider_trades')
    op.drop_table('insider_trades')
    op.drop_index(op.f('ix_insiders_cik'), table_name='insiders')
    op.drop_table('insiders')
    # ### end Alembic commands ###
