"""add hypothesis and hypothesis_run tables

Revision ID: 482eca4c6b8b
Revises: a52d091c5a4f
Create Date: 2026-09-20 21:43:41.196750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '482eca4c6b8b'
down_revision: Union[str, Sequence[str], None] = 'a52d091c5a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypotheses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypothesis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_id', sa.Uuid(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_window_start', sa.Date(), nullable=False),
    sa.Column('data_window_end', sa.Date(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_runs_hypothesis_id'), 'hypothesis_runs', ['hypothesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypothesis_runs_hypothesis_id'), table_name='hypothesis_runs')
    op.drop_table('hypothesis_runs')
    op.drop_table('hypotheses')
    # ### end Alembic commands ###
