"""initial schema

Revision ID: 55688045d1a3
Revises: 
Create Date: 2026-06-28 17:00:56.857159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55688045d1a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_cik'), 'institutions', ['cik'], unique=True)
    op.create_table('research_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_candidates_date'), 'research_candidates', ['date'], unique=False)
    op.create_table('research_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sentiment_direction', sa.String(length=16), nullable=False),
    sa.Column('full_report', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_reports_subject'), 'research_reports', ['subject'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_ticker_id'), 'alert_rules', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_table('filings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('filing_type', sa.String(length=16), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('edgar_url', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'filing_type', 'filed_date', 'edgar_url', name='uq_filing')
    )
    op.create_index(op.f('ix_filings_ticker_id'), 'filings', ['ticker_id'], unique=False)
    op.create_table('fundamentals_quarterly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'period', name='uq_fundamentals_ticker_period')
    )
    op.create_index(op.f('ix_fundamentals_quarterly_ticker_id'), 'fundamentals_quarterly', ['ticker_id'], unique=False)
    op.create_table('holdings_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('magnitude', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_changes_institution_id'), 'holdings_changes', ['institution_id'], unique=False)
    op.create_index(op.f('ix_holdings_changes_ticker_id'), 'holdings_changes', ['ticker_id'], unique=False)
    op.create_table('holdings_quarterly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'ticker_id', 'period', name='uq_holdings_inst_ticker_period')
    )
    op.create_index(op.f('ix_holdings_quarterly_institution_id'), 'holdings_quarterly', ['institution_id'], unique=False)
    op.create_index(op.f('ix_holdings_quarterly_ticker_id'), 'holdings_quarterly', ['ticker_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'timestamp', name='uq_price_history_ticker_ts')
    )
    op.create_index(op.f('ix_price_history_ticker_id'), 'price_history', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_table('research_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_sources_report_id'), 'research_sources', ['report_id'], unique=False)
    op.create_table('research_ticker_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.Column('exposure_type', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['research_reports.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_ticker_links_report_id'), 'research_ticker_links', ['report_id'], unique=False)
    op.create_index(op.f('ix_research_ticker_links_ticker_id'), 'research_ticker_links', ['ticker_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker_id', name='uq_watchlist_user_ticker')
    )
    op.create_index(op.f('ix_watchlists_ticker_id'), 'watchlists', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('alert_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_rule_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_log_alert_rule_id'), 'alert_log', ['alert_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_log_alert_rule_id'), table_name='alert_log')
    op.drop_table('alert_log')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_ticker_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_research_ticker_links_ticker_id'), table_name='research_ticker_links')
    op.drop_index(op.f('ix_research_ticker_links_report_id'), table_name='research_ticker_links')
    op.drop_table('research_ticker_links')
    op.drop_index(op.f('ix_research_sources_report_id'), table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_ticker_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_holdings_quarterly_ticker_id'), table_name='holdings_quarterly')
    op.drop_index(op.f('ix_holdings_quarterly_institution_id'), table_name='holdings_quarterly')
    op.drop_table('holdings_quarterly')
    op.drop_index(op.f('ix_holdings_changes_ticker_id'), table_name='holdings_changes')
    op.drop_index(op.f('ix_holdings_changes_institution_id'), table_name='holdings_changes')
    op.drop_table('holdings_changes')
    op.drop_index(op.f('ix_fundamentals_quarterly_ticker_id'), table_name='fundamentals_quarterly')
    op.drop_table('fundamentals_quarterly')
    op.drop_index(op.f('ix_filings_ticker_id'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_ticker_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_table('users')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_research_reports_subject'), table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_research_candidates_date'), table_name='research_candidates')
    op.drop_table('research_candidates')
    op.drop_index(op.f('ix_institutions_cik'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
