"""add legislators and congress_trades

Revision ID: 62a87c77a304
Revises: 2b1e04876168
Create Date: 2026-09-20 12:43:44.885414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62a87c77a304'
down_revision: Union[str, Sequence[str], None] = '2b1e04876168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('state_dst', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('congress_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legislator_id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.UUID(), nullable=True),
    sa.Column('doc_id', sa.String(length=20), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('transaction_type', sa.String(length=2), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('owner', sa.String(length=16), nullable=True),
    sa.Column('asset_description', sa.String(length=512), nullable=False),
    sa.Column('amount_low', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_high', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_unbounded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'line_no', name='uq_congress_trade_doc_line')
    )
    op.create_index(op.f('ix_congress_trades_doc_id'), 'congress_trades', ['doc_id'], unique=False)
    op.create_index(op.f('ix_congress_trades_filed_date'), 'congress_trades', ['filed_date'], unique=False)
    op.create_index(op.f('ix_congress_trades_legislator_id'), 'congress_trades', ['legislator_id'], unique=False)
    op.create_index(op.f('ix_congress_trades_ticker_id'), 'congress_trades', ['ticker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_congress_trades_ticker_id'), table_name='congress_trades')
    op.drop_index(op.f('ix_congress_trades_legislator_id'), table_name='congress_trades')
    op.drop_index(op.f('ix_congress_trades_filed_date'), table_name='congress_trades')
    op.drop_index(op.f('ix_congress_trades_doc_id'), table_name='congress_trades')
    op.drop_table('congress_trades')
    op.drop_table('legislators')
    # ### end Alembic commands ###
