"""add research chat context and messages

Revision ID: 925905c2b669
Revises: 62a87c77a304
Create Date: 2026-09-20 13:55:52.407173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925905c2b669'
down_revision: Union[str, Sequence[str], None] = '62a87c77a304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_chat_contexts',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('sources_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('research_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thinking', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_chat_messages_ticker'), 'research_chat_messages', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_chat_messages_ticker'), table_name='research_chat_messages')
    op.drop_table('research_chat_messages')
    op.drop_table('research_chat_contexts')
    # ### end Alembic commands ###
