"""add cusip to tickers

Revision ID: ce9845ffcb9a
Revises: 55688045d1a3
Create Date: 2026-06-28 18:10:29.146714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9845ffcb9a'
down_revision: Union[str, Sequence[str], None] = '55688045d1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('cusip', sa.String(length=9), nullable=True))
    op.create_unique_constraint(None, 'tickers', ['cusip'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickers', type_='unique')
    op.drop_column('tickers', 'cusip')
    # ### end Alembic commands ###
