"""add agent_verdicts table

Revision ID: eae855787324
Revises: 482eca4c6b8b
Create Date: 2026-09-20 22:02:31.652513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae855787324'
down_revision: Union[str, Sequence[str], None] = '482eca4c6b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_verdicts',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('bull_case', sa.Text(), nullable=False),
    sa.Column('bear_case', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('key_risks', sa.Text(), nullable=False),
    sa.Column('key_catalysts', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_verdicts')
    # ### end Alembic commands ###
